### Import essential libraries

In [1]:
import more_utils
more_utils.set_logging_level("INFO")

from IPython.display import display
from more_utils.persistence import ModelarDB
from more_utils.time_series import TimeseriesFactory

### Create connection to ModelarDB

Params:

1. hostname: ip adrress of the system where ModelarDB is running
2. interface: arrow (recommended), socket, http

In [2]:
conn_obj = ModelarDB.connect(
    hostname="localhost",
    manager_port=9998,
    edge_port=9999,
    cloud_port=9997,
    interface="arrow",
)

#### List tables in ModelarDB

In [9]:
conn_obj.list_tables()

['solar', 'solar2', 'windmill', 'test_table']

### Create timeseries factory instance

Factory instance can be used to access all the timeseries APIs.

In [3]:
ts_factory = TimeseriesFactory(source_db_conn=conn_obj)

### API: create_time_series()

#### 1. Fetch time-series data points for `model_table`.

Params:

- model_table (str): model table name.
- from_date (Union[str, None], optional): Start timestamp.
  Defaults to None.
- to_date (Union[str, None], optional): End timestamp.
  Defaults to None.
- limit (Union[int, None], optional): No of data points to fetch.
  Defaults to None.

#### 2. Retrieve data once time series object is created.

There are two ways to retireve data,

- fetch_next: retrieve data in batches
- fetch_all: retrieve all data at once

Time series data can be fetched in three dataframes,

- Pandas (fetch_type="pandas")
- JSON (fetch_type="json")
- PySpark (fetch_type="spark")

In [8]:
ts = ts_factory.create_time_series(model_table="solar2", limit=20)
for ts_batch in ts.fetch_next(fetch_type="pandas", batch_size=5):
    display(ts_batch.head())

,poa_irradiance,temperature,pv_module_isc,pv_module_pm,pv_module_imp,pv_module_vmp,pv_module_voc,pv_module_ff,delta_cmp,mt5_cabinet_temperature,...,relative_humidity,atmospheric_pressure,precipitation_accumulated,direct_normal_irradiance,global_horizontal_irradiance,diffuse_horizontal_irradiance,solar_qa_residual,pv_module_soiling_derate,delta_licor_poa,time_stamp
0,45.599998,23.600000,0.1130,1.279000,0.0931,13.732600,18.132999,62.439999,0.0,20.900000,...,86.699997,1016.900024,0.0,238.399994,81.900002,46.599998,3.4,0,0.1,2011-01-21 08:35:03.000
1,36.900002,25.200001,0.0820,0.856200,0.0664,12.901000,17.371300,60.080002,0.1,20.900000,...,93.099998,1010.099976,0.0,134.300003,48.799999,34.000000,-2.1,0,0.3,2011-01-21 09:35:25.784
2,1050.500000,45.599998,2.8423,43.111698,2.5946,16.615601,20.532000,73.870003,0.0,20.100000,...,61.099998,1021.500000,0.0,921.200012,849.000000,98.400002,-6.9,0,0.1,2011-03-11 22:43:35.864
3,787.099976,45.700001,2.1179,31.990999,1.9314,16.563299,20.293600,74.430000,0.3,22.799999,...,63.099998,1018.700012,0.0,760.799988,709.599976,172.100006,-4.2,0,0.1,2011-03-14 17:13:58.648
4,39.799999,21.100000,0.1173,1.347300,0.0969,13.904600,18.393801,62.439999,0.0,21.299999,...,85.900002,1006.599976,0.0,0.300000,46.599998,46.599998,0.0,0,0.0,2011-03-15 06:24:21.432

,poa_irradiance,temperature,pv_module_isc,pv_module_pm,pv_module_imp,pv_module_vmp,pv_module_voc,pv_module_ff,delta_cmp,mt5_cabinet_temperature,...,relative_humidity,atmospheric_pressure,precipitation_accumulated,direct_normal_irradiance,global_horizontal_irradiance,diffuse_horizontal_irradiance,solar_qa_residual,pv_module_soiling_derate,delta_licor_poa,time_stamp
0,200.399994,32.299999,0.4453,6.276400,0.3933,15.956400,19.567400,72.029999,0.0,20.200001,...,77.099998,1017.500000,0.0,579.400024,283.200012,72.199997,2.0,0,0.2,2011-03-15 09:09:42.216
1,881.799988,41.900002,2.3823,36.636700,2.1743,16.849600,20.638901,74.510002,0.4,27.700001,...,43.599998,1020.400024,0.0,821.000000,759.900024,145.399994,-7.6,0,0.2,2011-03-16 00:20:07.000
2,961.599976,52.099998,2.5893,37.923801,2.3508,16.132099,20.078100,72.949997,0.3,30.299999,...,39.400002,1015.299988,0.0,913.000000,995.900024,111.599998,-5.8,0,1.0,2011-03-16 00:35:29.784
3,247.399994,38.000000,0.6570,9.254200,0.5796,15.966600,19.510599,72.199997,0.1,24.299999,...,65.000000,1010.799988,0.0,29.600000,277.799988,254.899994,0.3,0,0.1,2011-03-16 20:45:50.568
4,341.000000,45.000000,0.9222,13.027700,0.8227,15.836000,19.376499,72.910004,1.5,22.299999,...,63.700001,1013.900024,0.0,16.400000,289.600006,278.200012,3.0,0,1.5,2011-05-05 09:34:02.648

,poa_irradiance,temperature,pv_module_isc,pv_module_pm,pv_module_imp,pv_module_vmp,pv_module_voc,pv_module_ff,delta_cmp,mt5_cabinet_temperature,...,relative_humidity,atmospheric_pressure,precipitation_accumulated,direct_normal_irradiance,global_horizontal_irradiance,diffuse_horizontal_irradiance,solar_qa_residual,pv_module_soiling_derate,delta_licor_poa,time_stamp
0,1041.599976,49.000000,2.8105,41.698799,2.5550,16.3202,20.337000,72.959999,0.6,29.700001,...,45.000000,1017.799988,0.0,853.500000,989.599976,179.100006,-5.8,0,3.0,2011-05-05 21:49:25.432
1,92.900002,26.400000,0.2593,3.381800,0.2198,15.3890,19.260099,67.720001,0.1,21.200001,...,88.199997,1014.400024,0.0,0.700000,110.500000,110.699997,0.5,0,0.1,2011-06-24 11:42:33.512
2,1192.699951,48.700001,3.2632,49.065102,2.9805,16.4622,20.601801,72.980003,0.3,22.400000,...,65.400002,1012.000000,0.0,848.000000,1124.500000,353.899994,-10.3,0,1.8,2011-06-26 05:57:56.296
3,315.399994,35.299999,0.7789,11.407500,0.6941,16.4361,19.978300,73.309998,4.2,29.900000,...,39.400002,1010.799988,0.0,356.100006,269.700012,134.300003,-0.0,0,1.4,2011-08-14 19:16:08.376
4,978.700012,45.400002,2.6727,40.206402,2.4370,16.4986,20.475100,73.470001,0.2,19.799999,...,52.200001,1018.799988,0.0,928.400024,661.599976,80.000000,-3.4,0,1.0,2011-10-03 08:49:18.456

,poa_irradiance,temperature,pv_module_isc,pv_module_pm,pv_module_imp,pv_module_vmp,pv_module_voc,pv_module_ff,delta_cmp,mt5_cabinet_temperature,...,relative_humidity,atmospheric_pressure,precipitation_accumulated,direct_normal_irradiance,global_horizontal_irradiance,diffuse_horizontal_irradiance,solar_qa_residual,pv_module_soiling_derate,delta_licor_poa,time_stamp
0,387.299988,38.400002,1.0319,15.250100,0.9267,16.456100,20.017599,73.830002,0.7,21.100000,...,55.900002,1017.900024,0.0,8.200000,381.100006,375.500000,1.2,0,0.3,2011-11-22 00:47:26.536
1,666.599976,39.000000,1.7729,27.400299,1.6189,16.925200,20.575001,75.110001,0.9,21.299999,...,40.000000,1007.700012,0.0,718.700012,549.099976,168.399994,-7.3,0,1.1,2011-11-22 11:42:49.320
2,524.900024,41.799999,1.3720,20.531900,1.2429,16.520000,20.084101,74.510002,1.2,26.299999,...,62.400002,1017.400024,0.0,767.599976,593.000000,106.400002,-5.5,0,0.5,2012-01-11 03:26:01.400
3,844.000000,35.099998,2.2697,36.238899,2.0838,17.390900,21.148100,75.500000,0.3,25.299999,...,33.900002,1015.200012,0.0,919.700012,595.099976,69.400002,-4.6,0,0.5,2012-01-11 20:41:24.184
4,348.100006,39.299999,0.9308,13.558100,0.8327,16.282101,19.828300,73.459999,0.2,24.100000,...,65.500000,1011.400024,0.0,238.300003,378.899994,220.300003,-1.9,0,0.1,2012-03-01 10:59:32.264

#### Retrieve all data at once.

In [7]:
ts = ts_factory.create_time_series(model_table="solar", limit=20)
ts.fetch_all(fetch_type="pandas")

,poa_irradiance,temperature,pv_module_isc,pv_module_pm,pv_module_imp,pv_module_vmp,pv_module_voc,pv_module_ff,delta_cmp,mt5_cabinet_temperature,...,relative_humidity,atmospheric_pressure,precipitation_accumulated,direct_normal_irradiance,global_horizontal_irradiance,diffuse_horizontal_irradiance,solar_qa_residual,pv_module_soiling_derate,delta_licor_poa,time_stamp
0,45.599998,23.600000,0.1130,1.279000,0.0931,13.732600,18.132999,62.439999,0.0,20.900000,...,86.699997,1016.900024,0.0,238.399994,81.900002,46.599998,3.4,0,0.1,2011-01-21 08:35:03.000
1,36.900002,25.200001,0.0820,0.856200,0.0664,12.901000,17.371300,60.080002,0.1,20.900000,...,93.099998,1010.099976,0.0,134.300003,48.799999,34.000000,-2.1,0,0.3,2011-01-21 09:35:25.784
2,1050.500000,45.599998,2.8423,43.111698,2.5946,16.615601,20.532000,73.870003,0.0,20.100000,...,61.099998,1021.500000,0.0,921.200012,849.000000,98.400002,-6.9,0,0.1,2011-03-11 22:43:35.864
3,787.099976,45.700001,2.1179,31.990999,1.9314,16.563299,20.293600,74.430000,0.3,22.799999,...,63.099998,1018.700012,0.0,760.799988,709.599976,172.100006,-4.2,0,0.1,2011-03-14 17:13:58.648
4,39.799999,21.100000,0.1173,1.347300,0.0969,13.904600,18.393801,62.439999,0.0,21.299999,...,85.900002,1006.599976,4.6,0.300000,46.599998,46.599998,0.0,0,0.0,2011-03-15 06:24:21.432
5,200.399994,32.299999,0.4453,6.276400,0.3933,15.956400,19.567400,72.029999,0.0,20.200001,...,77.099998,1017.500000,0.0,579.400024,283.200012,72.199997,2.0,0,0.2,2011-03-15 09:09:42.216
6,881.799988,41.900002,2.3823,36.636700,2.1743,16.849600,20.638901,74.510002,0.4,27.700001,...,43.599998,1020.400024,0.0,821.000000,759.900024,145.399994,-7.6,0,0.2,2011-03-16 00:20:07.000
7,961.599976,52.099998,2.5893,37.923801,2.3508,16.132099,20.078100,72.949997,0.3,30.299999,...,39.400002,1015.299988,0.0,913.000000,995.900024,111.599998,-5.8,0,1.0,2011-03-16 00:35:29.784
8,247.399994,38.000000,0.6570,9.254200,0.5796,15.966600,19.510599,72.199997,0.1,24.299999,...,65.000000,1010.799988,0.5,29.600000,277.799988,254.899994,0.3,0,0.1,2011-03-16 20:45:50.568
9,341.000000,45.000000,0.9222,13.027700,0.8227,15.836000,19.376499,72.910004,1.5,22.299999,...,63.700001,1013.900024,0.0,16.400000,289.600006,278.200012,3.0,0,1.5,2011-05-05 09:34:02.648
10,1041.599976,49.000000,2.8105,41.698799,2.5550,16.320200,20.337000,72.959999,0.6,29.700001,...,45.000000,1017.799988,0.0,853.500000,989.599976,179.100006,-5.8,0,3.0,2011-05-05 21:49:25.432
11,92.900002,26.400000,0.2593,3.381800,0.2198,15.389000,19.260099,67.720001,0.1,21.200001,...,88.199997,1014.400024,55.0,0.700000,110.500000,110.699997,0.5,0,0.1,2011-06-24 11:42:33.512
12,1192.699951,48.700001,3.2632,49.065102,2.9805,16.462200,20.601801,72.980003,0.3,22.400000,...,65.400002,1012.000000,0.0,848.000000,1124.500000,353.899994,-10.3,0,1.8,2011-06-26 05:57:56.296
13,315.399994,35.299999,0.7789,11.407500,0.6941,16.436100,19.978300,73.309998,4.2,29.900000,...,39.400002,1010.799988,0.0,356.100006,269.700012,134.300003,-0.0,0,1.4,2011-08-14 19:16:08.376
14,978.700012,45.400002,2.6727,40.206402,2.4370,16.498600,20.475100,73.470001,0.2,19.799999,...,52.200001,1018.799988,0.0,928.400024,661.599976,80.000000,-3.4,0,1.0,2011-10-03 08:49:18.456
15,387.299988,38.400002,1.0319,15.250100,0.9267,16.456100,20.017599,73.830002,0.7,21.100000,...,55.900002,1017.900024,0.5,8.200000,381.100006,375.500000,1.2,0,0.3,2011-11-22 00:47:26.536
16,666.599976,39.000000,1.7729,27.400299,1.6189,16.925200,20.575001,75.110001,0.9,21.299999,...,40.000000,1007.700012,0.0,718.700012,549.099976,168.399994,-7.3,0,1.1,2011-11-22 11:42:49.320
17,524.900024,41.799999,1.3720,20.531900,1.2429,16.520000,20.084101,74.510002,1.2,26.299999,...,62.400002,1017.400024,0.0,767.599976,593.000000,106.400002,-5.5,0,0.5,2012-01-11 03:26:01.400
18,844.000000,35.099998,2.2697,36.238899,2.0838,17.390900,21.148100,75.500000,0.3,25.299999,...,33.900002,1015.200012,0.0,919.700012,595.099976,69.400002,-4.6,0,0.5,2012-01-11 20:41:24.184
19,348.100006,39.299999,0.9308,13.558100,0.8327,16.282101,19.828300,73.459999,0.2,24.100000,...,65.500000,1011.400024,0.3,238.300003,378.899994,220.300003,-1.9,0,0.1,2012-03-01 10:59:32.264

#### Filter data by from_date, to_date and limit

In [22]:
ts = ts_factory.create_time_series(model_table="wind_turbine", from_date="2018-09-09 00:00:10", to_date="2018-09-09 00:00:20", limit=5)
ts.fetch_all(fetch_type="pandas")

,wind_speed,pitch_angle,rotor_speed,active_power,cos_nacelle_dir,sin_nacelle_dir,cos_wind_dir,sin_wind_dir,nacelle_direction,wind_direction,datetime
0,5.726736,0.0,8.879150,200.394608,-0.589247,-0.807951,-0.817803,-0.574907,233.893539,215.134491,2018-09-09 00:00:10
1,5.675937,0.0,8.885818,202.414261,-0.589247,-0.807951,-0.781470,-0.622759,233.893539,218.604599,2018-09-09 00:00:12
2,5.675937,0.0,8.892485,203.446259,-0.589247,-0.807951,-0.755213,-0.655069,233.893539,220.956055,2018-09-09 00:00:14
3,5.788526,0.0,8.899151,203.446259,-0.589247,-0.807951,-0.715746,-0.694715,233.893539,224.295654,2018-09-09 00:00:16
4,5.589014,0.0,8.905818,203.446259,-0.589247,-0.807951,-0.592048,-0.805692,233.893539,233.697540,2018-09-09 00:00:18

#### PySpark Dataframe

In [6]:
ts = ts_factory.create_time_series(model_table="wind_turbine", limit=20)
df = ts.fetch_all(fetch_type="spark")
df.show(5)

+-----------------+-----------+-----------------+------------------+-------------------+-------------------+-------------------+-------------------+-----------------+-----------------+-------------------+
|       wind_speed|pitch_angle|      rotor_speed|      active_power|    cos_nacelle_dir|    sin_nacelle_dir|       cos_wind_dir|       sin_wind_dir|nacelle_direction|   wind_direction|           datetime|
+-----------------+-----------+-----------------+------------------+-------------------+-------------------+-------------------+-------------------+-----------------+-----------------+-------------------+
|5.752687454223633|        0.0|8.852482795715332|406.09820556640625|0.11669249087572098|-0.1735512912273407| 0.5244066715240479|-0.6374121904373169|293.1658020019531|289.9858093261719|2018-09-09 00:00:02|
|5.665318012237549|        0.0|8.859149932861328| 400.8271789550781|0.11669249087572098|-0.1735512912273407| 0.6089133024215698|-0.5853030681610107|293.1658020019531|286.2523193359375|2018-09-09 00:00:04|
| 5.63350772857666|        0.0|8.865817070007324| 400.8271789550781|0.11669249087572098|-0.1735512912273407| 0.4837925136089325|-0.6036224961280823|293.1658020019531|272.0190734863281|2018-09-09 00:00:06|
| 5.63350772857666|        0.0|8.872483253479004| 392.6344909667969|0.11669249087572098|-0.1735512912273407|0.31555411219596863|-0.6036224961280823|293.1658020019531| 285.915771484375|2018-09-09 00:00:08|
|5.726736068725586|        0.0|   8.879150390625| 392.6344909667969|0.11669249087572098|-0.1735512912273407| 0.4918234050273895|-0.5919604897499084|293.1658020019531|307.0174255371094|2018-09-09 00:00:10|
+-----------------+-----------+-----------------+------------------+-------------------+-------------------+-------------------+-------------------+-----------------+-----------------+-------------------+
only showing top 5 rows

#### JSON Format

In [19]:
ts = ts_factory.create_time_series(model_table="wind_turbine", limit=20)
json_str = ts.fetch_all(fetch_type="json")
print(json_str)

{
    "columns": [
        "wind_speed",
        "pitch_angle",
        "rotor_speed",
        "active_power",
        "cos_nacelle_dir",
        "sin_nacelle_dir",
        "cos_wind_dir",
        "sin_wind_dir",
        "nacelle_direction",
        "wind_direction",
        "datetime"
    ],
    "data": [
        [
            5.752687454223633,
            0.0,
            8.852482795715332,
            406.09820556640625,
            0.11669249087572098,
            -0.1735512912273407,
            0.5244066715240479,
            -0.6374121904373169,
            293.1658020019531,
            289.9858093261719,
            "2018-09-09 00:00:02"
        ],
        [
            5.665318012237549,
            0.0,
            8.859149932861328,
            400.8271789550781,
            0.11669249087572098,
            -0.1735512912273407,
            0.6089133024215698,
            -0.5853030681610107,
            293.1658020019531,
            286.2523193359375,
            "2018-09-09 00:00:04"
        ],
        [
            5.63350772857666,
            0.0,
            8.865817070007324,
            400.8271789550781,
            0.11669249087572098,
            -0.1735512912273407,
            0.4837925136089325,
            -0.6036224961280823,
            293.1658020019531,
            272.0190734863281,
            "2018-09-09 00:00:06"
        ],
        [
            5.63350772857666,
            0.0,
            8.872483253479004,
            392.6344909667969,
            0.11669249087572098,
            -0.1735512912273407,
            0.31555411219596863,
            -0.6036224961280823,
            293.1658020019531,
            285.915771484375,
            "2018-09-09 00:00:08"
        ],
        [
            5.726736068725586,
            0.0,
            8.879150390625,
            392.6344909667969,
            0.11669249087572098,
            -0.1735512912273407,
            0.4918234050273895,
            -0.5919604897499084,
            293.1658020019531,
            307.0174255371094,
            "2018-09-09 00:00:10"
        ],
        [
            5.675936698913574,
            0.0,
            8.885817527770996,
            392.6344909667969,
            0.11669249087572098,
            -0.1735512912273407,
            0.4720349609851837,
            -0.5600778460502625,
            293.1658020019531,
            301.2775573730469,
            "2018-09-09 00:00:12"
        ],
        [
            5.675936698913574,
            0.0,
            8.892484664916992,
            392.6344909667969,
            0.11669249087572098,
            -0.1735512912273407,
            0.34404730796813965,
            -0.5256039500236511,
            293.1658020019531,
            297.9234313964844,
            "2018-09-09 00:00:14"
        ],
        [
            5.788525581359863,
            0.0,
            8.899150848388672,
            392.6344909667969,
            0.11669249087572098,
            -0.1735512912273407,
            0.18101909756660461,
            -0.46993258595466614,
            293.1658020019531,
            287.92449951171875,
            "2018-09-09 00:00:16"
        ],
        [
            5.589014053344727,
            0.0,
            8.905817985534668,
            392.6344909667969,
            0.11669249087572098,
            -0.1735512912273407,
            0.0871758982539177,
            -0.40493088960647583,
            293.1658020019531,
            276.53515625,
            "2018-09-09 00:00:18"
        ],
        [
            5.7154765129089355,
            0.0,
            8.912485122680664,
            392.6344909667969,
            0.11669249087572098,
            -0.1735512912273407,
            0.26300060749053955,
            -0.33099108934402466,
            293.1658020019531,
            269.94329833984375,
            "2018-09-09 00:00:20"
        ],
        [
            5.647541522979736,
            0.0,
            8.91915225982666,
            392.6344909667969,
            0.11669249087572098,
            -0.1735512912273407,
            0.48539242148399353,
            -0.39431342482566833,
            293.1658020019531,
            267.37066650390625,
            "2018-09-09 00:00:22"
        ],
        [
            5.612905979156494,
            0.0,
            8.92581844329834,
            392.6344909667969,
            0.11669249087572098,
            -0.1735512912273407,
            0.3189193904399872,
            -0.5289528369903564,
            293.1658020019531,
            267.37066650390625,
            "2018-09-09 00:00:24"
        ],
        [
            5.259332656860352,
            0.0,
            8.932485580444336,
            392.6344909667969,
            0.11669249087572098,
            -0.1735512912273407,
            0.2631133496761322,
            -0.6482066512107849,
            293.1658020019531,
            267.37066650390625,
            "2018-09-09 00:00:26"
        ],
        [
            5.338972091674805,
            0.0,
            8.939152717590332,
            392.6344909667969,
            0.11669249087572098,
            -0.1735512912273407,
            0.291060209274292,
            -0.5686754584312439,
            293.1658020019531,
            281.0544128417969,
            "2018-09-09 00:00:28"
        ],
        [
            5.480996131896973,
            0.0,
            8.945819854736328,
            388.94952392578125,
            0.11669249087572098,
            -0.1735512912273407,
            0.4173925220966339,
            -0.5609863996505737,
            293.1658020019531,
            264.92047119140625,
            "2018-09-09 00:00:30"
        ],
        [
            5.553999900817871,
            0.0,
            8.952486038208008,
            385.50018310546875,
            0.11669249087572098,
            -0.1735512912273407,
            0.3364315330982208,
            -0.46180978417396545,
            293.1658020019531,
            267.99615478515625,
            "2018-09-09 00:00:32"
        ],
        [
            5.308352470397949,
            0.0,
            8.959153175354004,
            385.50018310546875,
            0.11669249087572098,
            -0.1735512912273407,
            0.1775244027376175,
            -0.42810776829719543,
            293.1658020019531,
            263.34893798828125,
            "2018-09-09 00:00:34"
        ],
        [
            5.509964942932129,
            0.0,
            8.9658203125,
            382.2016906738281,
            0.11669249087572098,
            -0.1735512912273407,
            0.16848839819431305,
            -0.5020846724510193,
            293.1658020019531,
            257.3612365722656,
            "2018-09-09 00:00:36"
        ],
        [
            5.613729476928711,
            0.0,
            8.972487449645996,
            379.79888916015625,
            0.11669249087572098,
            -0.1735512912273407,
            0.15964050590991974,
            -0.4724918007850647,
            293.1658020019531,
            258.7225341796875,
            "2018-09-09 00:00:38"
        ],
        [
            5.390326499938965,
            0.0,
            8.979154586791992,
            379.79888916015625,
            0.11669249087572098,
            -0.1735512912273407,
            0.17954103648662567,
            -0.4838304817676544,
            293.1658020019531,
            260.9974670410156,
            "2018-09-09 00:00:40"
        ]
    ]
}