### Import essential libraries

In [7]:
import more_utils
more_utils.set_logging_level("INFO")

from IPython.display import display
from more_utils.persistence import ModelarDB
from more_utils.time_series import TimeseriesFactory

### Create connection to ModelarDB

Params:

1. hostname: ip adrress of the system where ModelarDB is running
2. interface: arrow (recommended), socket, http

In [8]:
conn_obj = ModelarDB.connect(hostname="83.212.75.52", port=31000, interface="arrow")

### Create timeseries factory instance

Factory instance can be used to access all the timeseries APIs.

In [9]:
ts_factory = TimeseriesFactory(source_db_conn=conn_obj)

### API: create_time_series()

#### 1. Fetch time-series data points for `model_table`.

Params:

- model_table (str): model table name.
- from_date (Union[str, None], optional): Start timestamp.
  Defaults to None.
- to_date (Union[str, None], optional): End timestamp.
  Defaults to None.
- limit (Union[int, None], optional): No of data points to fetch.
  Defaults to None.

#### 2. Retrieve data once time series object is created.

There are two ways to retireve data,

- fetch_next: retrieve data in batches
- fetch_all: retrieve all data at once

Time series data can be fetched in three dataframes,

- Pandas (fetch_type="pandas")
- JSON (fetch_type="json")
- PySpark (fetch_type="spark")

In [10]:
ts = ts_factory.create_time_series(model_table="wind_turbine_2", limit=20)
for ts_batch in ts.fetch_next(fetch_type="pandas", batch_size=5):
    display(ts_batch.head())

,wind_speed,pitch_angle,rotor_speed,active_power,cos_nacelle_dir,sin_nacelle_dir,cos_wind_dir,sin_wind_dir,nacelle_direction,wind_direction,datetime
0,4.209886,0.832224,9.74053,406.098206,-0.589247,-0.807951,0.976749,0.693032,293.165802,229.543091,2018-10-03 06:32:36
1,4.209886,0.805292,9.74053,400.827179,-0.589247,-0.807951,0.976749,0.697270,293.165802,222.196228,2018-10-03 06:32:38
2,4.312740,0.778361,9.74053,400.827179,-0.589247,-0.807951,0.983288,0.673945,293.165802,218.535812,2018-10-03 06:32:40
3,4.407039,0.751429,9.74053,392.634491,-0.589247,-0.807951,0.993522,0.695470,293.165802,216.650330,2018-10-03 06:32:42
4,4.664524,0.724497,9.74053,392.634491,-0.589247,-0.807951,0.998582,0.738995,293.165802,215.134491,2018-10-03 06:32:44

,wind_speed,pitch_angle,rotor_speed,active_power,cos_nacelle_dir,sin_nacelle_dir,cos_wind_dir,sin_wind_dir,nacelle_direction,wind_direction,datetime
0,4.990037,0.697566,9.74053,392.634491,-0.589247,-0.807951,0.998582,0.790329,293.165802,218.604599,2018-10-03 06:32:46
1,4.335406,0.670634,9.74053,392.634491,-0.589247,-0.807951,0.998582,0.790329,293.165802,220.956055,2018-10-03 06:32:48
2,3.793854,0.643702,9.74053,392.634491,-0.589247,-0.807951,0.998582,0.725485,293.165802,224.295654,2018-10-03 06:32:50
3,3.793854,0.616771,9.74053,392.634491,-0.589247,-0.807951,0.998582,0.523061,293.165802,233.697540,2018-10-03 06:32:52
4,3.945287,0.589839,9.74053,392.634491,-0.589247,-0.807951,0.991791,0.529919,293.165802,230.689606,2018-10-03 06:32:54

,wind_speed,pitch_angle,rotor_speed,active_power,cos_nacelle_dir,sin_nacelle_dir,cos_wind_dir,sin_wind_dir,nacelle_direction,wind_direction,datetime
0,4.261750,0.562908,9.74053,392.634491,-0.589247,-0.807951,0.991791,0.575343,293.165802,228.013840,2018-10-03 06:32:56
1,4.159927,0.535976,9.74053,392.634491,-0.589247,-0.807951,0.975381,0.634441,293.165802,222.500656,2018-10-03 06:32:58
2,3.911407,0.509044,9.74053,392.634491,-0.589247,-0.807951,0.946405,0.658338,293.165802,214.977539,2018-10-03 06:33:00
3,3.978015,0.499747,9.74053,392.634491,-0.589247,-0.807951,0.976920,0.690160,293.165802,212.209900,2018-10-03 06:33:02
4,4.108066,0.499498,9.74053,388.949524,-0.589247,-0.807951,0.989966,0.722899,293.165802,226.017532,2018-10-03 06:33:04

,wind_speed,pitch_angle,rotor_speed,active_power,cos_nacelle_dir,sin_nacelle_dir,cos_wind_dir,sin_wind_dir,nacelle_direction,wind_direction,datetime
0,4.265428,0.499249,9.74053,385.500183,-0.589247,-0.807951,0.996299,0.743994,293.165802,227.332687,2018-10-03 06:33:06
1,4.671745,0.499000,9.74053,385.500183,-0.589247,-0.807951,0.996299,0.777163,293.165802,223.535812,2018-10-03 06:33:08
2,4.773427,0.498751,9.74053,382.201691,-0.589247,-0.807951,0.988755,0.794445,293.165802,225.413773,2018-10-03 06:33:10
3,4.773427,0.498502,9.74053,379.798889,-0.589247,-0.807951,0.980937,0.718679,293.165802,223.304291,2018-10-03 06:33:12
4,5.284554,0.498254,9.74053,379.798889,-0.589247,-0.807951,0.980937,0.664633,293.165802,219.326630,2018-10-03 06:33:14

In [16]:
ts = ts_factory.create_time_series(model_table="wind_turbine", limit=20)
ts.fetch_all(fetch_type="pandas")

,wind_speed,pitch_angle,rotor_speed,active_power,cos_nacelle_dir,sin_nacelle_dir,cos_wind_dir,sin_wind_dir,nacelle_direction,wind_direction,datetime
0,5.752687,0.0,8.852483,406.098206,0.116692,-0.173551,0.524407,-0.637412,293.165802,289.985809,2018-09-09 00:00:02
1,5.665318,0.0,8.859150,400.827179,0.116692,-0.173551,0.608913,-0.585303,293.165802,286.252319,2018-09-09 00:00:04
2,5.633508,0.0,8.865817,400.827179,0.116692,-0.173551,0.483793,-0.603622,293.165802,272.019073,2018-09-09 00:00:06
3,5.633508,0.0,8.872483,392.634491,0.116692,-0.173551,0.315554,-0.603622,293.165802,285.915771,2018-09-09 00:00:08
4,5.726736,0.0,8.879150,392.634491,0.116692,-0.173551,0.491823,-0.591960,293.165802,307.017426,2018-09-09 00:00:10
5,5.675937,0.0,8.885818,392.634491,0.116692,-0.173551,0.472035,-0.560078,293.165802,301.277557,2018-09-09 00:00:12
6,5.675937,0.0,8.892485,392.634491,0.116692,-0.173551,0.344047,-0.525604,293.165802,297.923431,2018-09-09 00:00:14
7,5.788526,0.0,8.899151,392.634491,0.116692,-0.173551,0.181019,-0.469933,293.165802,287.924500,2018-09-09 00:00:16
8,5.589014,0.0,8.905818,392.634491,0.116692,-0.173551,0.087176,-0.404931,293.165802,276.535156,2018-09-09 00:00:18
9,5.715477,0.0,8.912485,392.634491,0.116692,-0.173551,0.263001,-0.330991,293.165802,269.943298,2018-09-09 00:00:20
10,5.647542,0.0,8.919152,392.634491,0.116692,-0.173551,0.485392,-0.394313,293.165802,267.370667,2018-09-09 00:00:22
11,5.612906,0.0,8.925818,392.634491,0.116692,-0.173551,0.318919,-0.528953,293.165802,267.370667,2018-09-09 00:00:24
12,5.259333,0.0,8.932486,392.634491,0.116692,-0.173551,0.263113,-0.648207,293.165802,267.370667,2018-09-09 00:00:26
13,5.338972,0.0,8.939153,392.634491,0.116692,-0.173551,0.291060,-0.568675,293.165802,281.054413,2018-09-09 00:00:28
14,5.480996,0.0,8.945820,388.949524,0.116692,-0.173551,0.417393,-0.560986,293.165802,264.920471,2018-09-09 00:00:30
15,5.554000,0.0,8.952486,385.500183,0.116692,-0.173551,0.336432,-0.461810,293.165802,267.996155,2018-09-09 00:00:32
16,5.308352,0.0,8.959153,385.500183,0.116692,-0.173551,0.177524,-0.428108,293.165802,263.348938,2018-09-09 00:00:34
17,5.509965,0.0,8.965820,382.201691,0.116692,-0.173551,0.168488,-0.502085,293.165802,257.361237,2018-09-09 00:00:36
18,5.613729,0.0,8.972487,379.798889,0.116692,-0.173551,0.159641,-0.472492,293.165802,258.722534,2018-09-09 00:00:38
19,5.390326,0.0,8.979155,379.798889,0.116692,-0.173551,0.179541,-0.483830,293.165802,260.997467,2018-09-09 00:00:40

In [22]:
ts = ts_factory.create_time_series(model_table="wind_turbine", from_date="2018-09-09 00:00:10", to_date="2018-09-09 00:00:20", limit=5)
ts.fetch_all(fetch_type="pandas")

,wind_speed,pitch_angle,rotor_speed,active_power,cos_nacelle_dir,sin_nacelle_dir,cos_wind_dir,sin_wind_dir,nacelle_direction,wind_direction,datetime
0,5.726736,0.0,8.879150,200.394608,-0.589247,-0.807951,-0.817803,-0.574907,233.893539,215.134491,2018-09-09 00:00:10
1,5.675937,0.0,8.885818,202.414261,-0.589247,-0.807951,-0.781470,-0.622759,233.893539,218.604599,2018-09-09 00:00:12
2,5.675937,0.0,8.892485,203.446259,-0.589247,-0.807951,-0.755213,-0.655069,233.893539,220.956055,2018-09-09 00:00:14
3,5.788526,0.0,8.899151,203.446259,-0.589247,-0.807951,-0.715746,-0.694715,233.893539,224.295654,2018-09-09 00:00:16
4,5.589014,0.0,8.905818,203.446259,-0.589247,-0.807951,-0.592048,-0.805692,233.893539,233.697540,2018-09-09 00:00:18

#### PySpark Dataframe

In [6]:
ts = ts_factory.create_time_series(model_table="wind_turbine", limit=20)
df = ts.fetch_all(fetch_type="spark")
df.show(5)

+-----------------+-----------+-----------------+------------------+-------------------+-------------------+-------------------+-------------------+-----------------+-----------------+-------------------+
|       wind_speed|pitch_angle|      rotor_speed|      active_power|    cos_nacelle_dir|    sin_nacelle_dir|       cos_wind_dir|       sin_wind_dir|nacelle_direction|   wind_direction|           datetime|
+-----------------+-----------+-----------------+------------------+-------------------+-------------------+-------------------+-------------------+-----------------+-----------------+-------------------+
|5.752687454223633|        0.0|8.852482795715332|406.09820556640625|0.11669249087572098|-0.1735512912273407| 0.5244066715240479|-0.6374121904373169|293.1658020019531|289.9858093261719|2018-09-09 00:00:02|
|5.665318012237549|        0.0|8.859149932861328| 400.8271789550781|0.11669249087572098|-0.1735512912273407| 0.6089133024215698|-0.5853030681610107|293.1658020019531|286.2523193359375|2018-09-09 00:00:04|
| 5.63350772857666|        0.0|8.865817070007324| 400.8271789550781|0.11669249087572098|-0.1735512912273407| 0.4837925136089325|-0.6036224961280823|293.1658020019531|272.0190734863281|2018-09-09 00:00:06|
| 5.63350772857666|        0.0|8.872483253479004| 392.6344909667969|0.11669249087572098|-0.1735512912273407|0.31555411219596863|-0.6036224961280823|293.1658020019531| 285.915771484375|2018-09-09 00:00:08|
|5.726736068725586|        0.0|   8.879150390625| 392.6344909667969|0.11669249087572098|-0.1735512912273407| 0.4918234050273895|-0.5919604897499084|293.1658020019531|307.0174255371094|2018-09-09 00:00:10|
+-----------------+-----------+-----------------+------------------+-------------------+-------------------+-------------------+-------------------+-----------------+-----------------+-------------------+
only showing top 5 rows

#### JSON Format

In [19]:
ts = ts_factory.create_time_series(model_table="wind_turbine", limit=20)
json_str = ts.fetch_all(fetch_type="json")
print(json_str)

{
    "columns": [
        "wind_speed",
        "pitch_angle",
        "rotor_speed",
        "active_power",
        "cos_nacelle_dir",
        "sin_nacelle_dir",
        "cos_wind_dir",
        "sin_wind_dir",
        "nacelle_direction",
        "wind_direction",
        "datetime"
    ],
    "data": [
        [
            5.752687454223633,
            0.0,
            8.852482795715332,
            406.09820556640625,
            0.11669249087572098,
            -0.1735512912273407,
            0.5244066715240479,
            -0.6374121904373169,
            293.1658020019531,
            289.9858093261719,
            "2018-09-09 00:00:02"
        ],
        [
            5.665318012237549,
            0.0,
            8.859149932861328,
            400.8271789550781,
            0.11669249087572098,
            -0.1735512912273407,
            0.6089133024215698,
            -0.5853030681610107,
            293.1658020019531,
            286.2523193359375,
            "2018-09-09 00:00:04"
        ],
        [
            5.63350772857666,
            0.0,
            8.865817070007324,
            400.8271789550781,
            0.11669249087572098,
            -0.1735512912273407,
            0.4837925136089325,
            -0.6036224961280823,
            293.1658020019531,
            272.0190734863281,
            "2018-09-09 00:00:06"
        ],
        [
            5.63350772857666,
            0.0,
            8.872483253479004,
            392.6344909667969,
            0.11669249087572098,
            -0.1735512912273407,
            0.31555411219596863,
            -0.6036224961280823,
            293.1658020019531,
            285.915771484375,
            "2018-09-09 00:00:08"
        ],
        [
            5.726736068725586,
            0.0,
            8.879150390625,
            392.6344909667969,
            0.11669249087572098,
            -0.1735512912273407,
            0.4918234050273895,
            -0.5919604897499084,
            293.1658020019531,
            307.0174255371094,
            "2018-09-09 00:00:10"
        ],
        [
            5.675936698913574,
            0.0,
            8.885817527770996,
            392.6344909667969,
            0.11669249087572098,
            -0.1735512912273407,
            0.4720349609851837,
            -0.5600778460502625,
            293.1658020019531,
            301.2775573730469,
            "2018-09-09 00:00:12"
        ],
        [
            5.675936698913574,
            0.0,
            8.892484664916992,
            392.6344909667969,
            0.11669249087572098,
            -0.1735512912273407,
            0.34404730796813965,
            -0.5256039500236511,
            293.1658020019531,
            297.9234313964844,
            "2018-09-09 00:00:14"
        ],
        [
            5.788525581359863,
            0.0,
            8.899150848388672,
            392.6344909667969,
            0.11669249087572098,
            -0.1735512912273407,
            0.18101909756660461,
            -0.46993258595466614,
            293.1658020019531,
            287.92449951171875,
            "2018-09-09 00:00:16"
        ],
        [
            5.589014053344727,
            0.0,
            8.905817985534668,
            392.6344909667969,
            0.11669249087572098,
            -0.1735512912273407,
            0.0871758982539177,
            -0.40493088960647583,
            293.1658020019531,
            276.53515625,
            "2018-09-09 00:00:18"
        ],
        [
            5.7154765129089355,
            0.0,
            8.912485122680664,
            392.6344909667969,
            0.11669249087572098,
            -0.1735512912273407,
            0.26300060749053955,
            -0.33099108934402466,
            293.1658020019531,
            269.94329833984375,
            "2018-09-09 00:00:20"
        ],
        [
            5.647541522979736,
            0.0,
            8.91915225982666,
            392.6344909667969,
            0.11669249087572098,
            -0.1735512912273407,
            0.48539242148399353,
            -0.39431342482566833,
            293.1658020019531,
            267.37066650390625,
            "2018-09-09 00:00:22"
        ],
        [
            5.612905979156494,
            0.0,
            8.92581844329834,
            392.6344909667969,
            0.11669249087572098,
            -0.1735512912273407,
            0.3189193904399872,
            -0.5289528369903564,
            293.1658020019531,
            267.37066650390625,
            "2018-09-09 00:00:24"
        ],
        [
            5.259332656860352,
            0.0,
            8.932485580444336,
            392.6344909667969,
            0.11669249087572098,
            -0.1735512912273407,
            0.2631133496761322,
            -0.6482066512107849,
            293.1658020019531,
            267.37066650390625,
            "2018-09-09 00:00:26"
        ],
        [
            5.338972091674805,
            0.0,
            8.939152717590332,
            392.6344909667969,
            0.11669249087572098,
            -0.1735512912273407,
            0.291060209274292,
            -0.5686754584312439,
            293.1658020019531,
            281.0544128417969,
            "2018-09-09 00:00:28"
        ],
        [
            5.480996131896973,
            0.0,
            8.945819854736328,
            388.94952392578125,
            0.11669249087572098,
            -0.1735512912273407,
            0.4173925220966339,
            -0.5609863996505737,
            293.1658020019531,
            264.92047119140625,
            "2018-09-09 00:00:30"
        ],
        [
            5.553999900817871,
            0.0,
            8.952486038208008,
            385.50018310546875,
            0.11669249087572098,
            -0.1735512912273407,
            0.3364315330982208,
            -0.46180978417396545,
            293.1658020019531,
            267.99615478515625,
            "2018-09-09 00:00:32"
        ],
        [
            5.308352470397949,
            0.0,
            8.959153175354004,
            385.50018310546875,
            0.11669249087572098,
            -0.1735512912273407,
            0.1775244027376175,
            -0.42810776829719543,
            293.1658020019531,
            263.34893798828125,
            "2018-09-09 00:00:34"
        ],
        [
            5.509964942932129,
            0.0,
            8.9658203125,
            382.2016906738281,
            0.11669249087572098,
            -0.1735512912273407,
            0.16848839819431305,
            -0.5020846724510193,
            293.1658020019531,
            257.3612365722656,
            "2018-09-09 00:00:36"
        ],
        [
            5.613729476928711,
            0.0,
            8.972487449645996,
            379.79888916015625,
            0.11669249087572098,
            -0.1735512912273407,
            0.15964050590991974,
            -0.4724918007850647,
            293.1658020019531,
            258.7225341796875,
            "2018-09-09 00:00:38"
        ],
        [
            5.390326499938965,
            0.0,
            8.979154586791992,
            379.79888916015625,
            0.11669249087572098,
            -0.1735512912273407,
            0.17954103648662567,
            -0.4838304817676544,
            293.1658020019531,
            260.9974670410156,
            "2018-09-09 00:00:40"
        ]
    ]
}